name: url_launcher_macos
publish_to: none
description: macOS implementation of the url_launcher plugin.
repository: https://github.com/flutter/packages/tree/main/packages/url_launcher/url_launcher_macos
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+url_launcher%22
version: 3.0.7

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.13.0"

flutter:
  plugin:
    implements: url_launcher
    platforms:
      macos:
        pluginClass: UrlLauncherPlugin
        fileName: url_launcher_macos.dart
        dartPluginClass: UrlLauncherMacOS

dependencies:
  flutter:
    sdk: flutter
  url_launcher_platform_interface: 
    git: https://github.com/kumsumit/url_launcher_platform_interface.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  pigeon: 
    git: https://github.com/kumsumit/pigeon.git
  test: ^1.16.3

topics:
  - links
  - os-integration
  - url-launcher
  - urls
